site_name: KooRender Docs
site_url: https://koorender.com/docs/
site_dir: site/docs/zh
docs_dir: docs

theme:
  name: material
  custom_dir: overrides
  logo: https://qhstaticssl.kujiale.com/image/png/1773645165382/F724EB380400904A6B7BE7EB0000504A.png
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
  palette:
    - scheme: default
      primary: blue
      accent: light-blue
      
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://koorender.com/
    - icon: fontawesome/brands/github
      link: https://github.com/manycoretech/koorender-max
      
plugins:
  - search

nav:
  - 首页: index.md
  - 快速开始: start.md
  - 使用教程: guide.md
  - 高级配置: config.md

markdown_extensions:
  - toc:
      permalink: true