site_name: KooRender 文档中心
site_url: https://koorender.com/
site_dir: site/docs

theme:
  name: material
  logo: https://qhstaticssl.kujiale.com/image/png/1773645150581/BA3B65894F8E28BA0943CD08F6EC9DC3.png
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
  palette:
    scheme: default
    primary: blue
    accent: blue
    
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://koorender.com/

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true

nav:
  - 首页: index.md
  - 快速开始: start.md
  - 使用教程: guide.md
  - 高级配置: config.md