site_name: 文档中心
site_url: https://koorender.com/
site_dir: site/docs

theme:
  name: material
  logo: https://qhstaticssl.kujiale.com/image/png/1773645165382/F724EB380400904A6B7BE7EB0000504A.png
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
  palette:
    scheme: default
    primary: blue
    accent: blue
    
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://koorender.com/
    - icon: fontawesome/brands/github
      link: https://github.com/manycoretech/koorender-max

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true

nav:
  - 首页: index.md
  - 快速开始: start.md
  - 使用教程: guide.md
  - 高级配置: config.md